<?php

/**
 * Baseblog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property text $metadescription
 * @property text $metakeywords
 * @property text $content
 * @property string $filename
 * @property boolean $active
 * @property boolean $deleted
 * @property datetime $publish_bate
 * 
 * @method integer  getId()              Returns the current record's "id" value
 * @method string   getTitle()           Returns the current record's "title" value
 * @method text     getMetadescription() Returns the current record's "metadescription" value
 * @method text     getMetakeywords()    Returns the current record's "metakeywords" value
 * @method text     getContent()         Returns the current record's "content" value
 * @method string   getFilename()        Returns the current record's "filename" value
 * @method boolean  getActive()          Returns the current record's "active" value
 * @method boolean  getDeleted()         Returns the current record's "deleted" value
 * @method datetime getPublishBate()     Returns the current record's "publish_bate" value
 * @method blog     setId()              Sets the current record's "id" value
 * @method blog     setTitle()           Sets the current record's "title" value
 * @method blog     setMetadescription() Sets the current record's "metadescription" value
 * @method blog     setMetakeywords()    Sets the current record's "metakeywords" value
 * @method blog     setContent()         Sets the current record's "content" value
 * @method blog     setFilename()        Sets the current record's "filename" value
 * @method blog     setActive()          Sets the current record's "active" value
 * @method blog     setDeleted()         Sets the current record's "deleted" value
 * @method blog     setPublishBate()     Sets the current record's "publish_bate" value
 * 
 * @package    Golf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseblog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('metadescription', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('metakeywords', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('filename', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('deleted', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('publish_bate', 'datetime', null, array(
             'type' => 'datetime',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}