<?php

/**
 * Basecourse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $course_id
 * @property string $tees_id
 * @property string $CourseName
 * @property string $StreetAddress
 * @property string $City
 * @property string $StateorRegion
 * @property string $Zip
 * @property string $County
 * @property string $PhoneNumber
 * @property string $FaxNumber
 * @property string $URL
 * @property string $TotalHoles
 * @property string $architects
 * @property string $YearBuiltFounded
 * @property string $StatusPublicPrivateResort
 * @property string $GuestPolicy
 * @property string $EmailAddress
 * @property integer $TeeNumber
 * @property string $teename
 * @property integer $Par
 * @property integer $Holes
 * @property float $Rating
 * @property integer $Slope
 * @property integer $Par_1
 * @property integer $Yards_1
 * @property integer $Hdcp_1
 * @property integer $Par_2
 * @property integer $Yards_2
 * @property integer $Hdcp_2
 * @property integer $Par_3
 * @property integer $Yards_3
 * @property integer $Hdcp_3
 * @property integer $Par_4
 * @property integer $Yards_4
 * @property integer $Hdcp_4
 * @property integer $Par_5
 * @property integer $Yards_5
 * @property integer $Hdcp_5
 * @property integer $Par_6
 * @property integer $Yards_6
 * @property integer $Hdcp_6
 * @property integer $Par_7
 * @property integer $Yards_7
 * @property integer $Hdcp_7
 * @property integer $Par_8
 * @property integer $Yards_8
 * @property integer $Hdcp_8
 * @property integer $Par_9
 * @property integer $Yards_9
 * @property integer $Hdcp_9
 * @property integer $Par_10
 * @property integer $Yards_10
 * @property integer $Hdcp_10
 * @property integer $Par_11
 * @property integer $Yards_11
 * @property integer $Hdcp_11
 * @property integer $Par_12
 * @property integer $Yards_12
 * @property integer $Hdcp_12
 * @property integer $Par_13
 * @property integer $Yards_13
 * @property integer $Hdcp_13
 * @property integer $Par_14
 * @property integer $Yards_14
 * @property integer $Hdcp_14
 * @property integer $Par_15
 * @property integer $Yards_15
 * @property integer $Hdcp_15
 * @property integer $Par_16
 * @property integer $Yards_16
 * @property integer $Hdcp_16
 * @property integer $Par_17
 * @property integer $Yards_17
 * @property integer $Hdcp_17
 * @property integer $Par_18
 * @property integer $Yards_18
 * @property integer $Hdcp_18
 * @property integer $Tot_in_par
 * @property integer $Tot_in_yards
 * @property integer $Length
 * @property double $latitude
 * @property double $longitude
 * @property Doctrine_Collection $Events
 * 
 * @method string              getCourseId()                  Returns the current record's "course_id" value
 * @method string              getTeesId()                    Returns the current record's "tees_id" value
 * @method string              getCourseName()                Returns the current record's "CourseName" value
 * @method string              getStreetAddress()             Returns the current record's "StreetAddress" value
 * @method string              getCity()                      Returns the current record's "City" value
 * @method string              getStateorRegion()             Returns the current record's "StateorRegion" value
 * @method string              getZip()                       Returns the current record's "Zip" value
 * @method string              getCounty()                    Returns the current record's "County" value
 * @method string              getPhoneNumber()               Returns the current record's "PhoneNumber" value
 * @method string              getFaxNumber()                 Returns the current record's "FaxNumber" value
 * @method string              getURL()                       Returns the current record's "URL" value
 * @method string              getTotalHoles()                Returns the current record's "TotalHoles" value
 * @method string              getArchitects()                Returns the current record's "architects" value
 * @method string              getYearBuiltFounded()          Returns the current record's "YearBuiltFounded" value
 * @method string              getStatusPublicPrivateResort() Returns the current record's "StatusPublicPrivateResort" value
 * @method string              getGuestPolicy()               Returns the current record's "GuestPolicy" value
 * @method string              getEmailAddress()              Returns the current record's "EmailAddress" value
 * @method integer             getTeeNumber()                 Returns the current record's "TeeNumber" value
 * @method string              getTeename()                   Returns the current record's "teename" value
 * @method integer             getPar()                       Returns the current record's "Par" value
 * @method integer             getHoles()                     Returns the current record's "Holes" value
 * @method float               getRating()                    Returns the current record's "Rating" value
 * @method integer             getSlope()                     Returns the current record's "Slope" value
 * @method integer             getPar1()                      Returns the current record's "Par_1" value
 * @method integer             getYards1()                    Returns the current record's "Yards_1" value
 * @method integer             getHdcp1()                     Returns the current record's "Hdcp_1" value
 * @method integer             getPar2()                      Returns the current record's "Par_2" value
 * @method integer             getYards2()                    Returns the current record's "Yards_2" value
 * @method integer             getHdcp2()                     Returns the current record's "Hdcp_2" value
 * @method integer             getPar3()                      Returns the current record's "Par_3" value
 * @method integer             getYards3()                    Returns the current record's "Yards_3" value
 * @method integer             getHdcp3()                     Returns the current record's "Hdcp_3" value
 * @method integer             getPar4()                      Returns the current record's "Par_4" value
 * @method integer             getYards4()                    Returns the current record's "Yards_4" value
 * @method integer             getHdcp4()                     Returns the current record's "Hdcp_4" value
 * @method integer             getPar5()                      Returns the current record's "Par_5" value
 * @method integer             getYards5()                    Returns the current record's "Yards_5" value
 * @method integer             getHdcp5()                     Returns the current record's "Hdcp_5" value
 * @method integer             getPar6()                      Returns the current record's "Par_6" value
 * @method integer             getYards6()                    Returns the current record's "Yards_6" value
 * @method integer             getHdcp6()                     Returns the current record's "Hdcp_6" value
 * @method integer             getPar7()                      Returns the current record's "Par_7" value
 * @method integer             getYards7()                    Returns the current record's "Yards_7" value
 * @method integer             getHdcp7()                     Returns the current record's "Hdcp_7" value
 * @method integer             getPar8()                      Returns the current record's "Par_8" value
 * @method integer             getYards8()                    Returns the current record's "Yards_8" value
 * @method integer             getHdcp8()                     Returns the current record's "Hdcp_8" value
 * @method integer             getPar9()                      Returns the current record's "Par_9" value
 * @method integer             getYards9()                    Returns the current record's "Yards_9" value
 * @method integer             getHdcp9()                     Returns the current record's "Hdcp_9" value
 * @method integer             getPar10()                     Returns the current record's "Par_10" value
 * @method integer             getYards10()                   Returns the current record's "Yards_10" value
 * @method integer             getHdcp10()                    Returns the current record's "Hdcp_10" value
 * @method integer             getPar11()                     Returns the current record's "Par_11" value
 * @method integer             getYards11()                   Returns the current record's "Yards_11" value
 * @method integer             getHdcp11()                    Returns the current record's "Hdcp_11" value
 * @method integer             getPar12()                     Returns the current record's "Par_12" value
 * @method integer             getYards12()                   Returns the current record's "Yards_12" value
 * @method integer             getHdcp12()                    Returns the current record's "Hdcp_12" value
 * @method integer             getPar13()                     Returns the current record's "Par_13" value
 * @method integer             getYards13()                   Returns the current record's "Yards_13" value
 * @method integer             getHdcp13()                    Returns the current record's "Hdcp_13" value
 * @method integer             getPar14()                     Returns the current record's "Par_14" value
 * @method integer             getYards14()                   Returns the current record's "Yards_14" value
 * @method integer             getHdcp14()                    Returns the current record's "Hdcp_14" value
 * @method integer             getPar15()                     Returns the current record's "Par_15" value
 * @method integer             getYards15()                   Returns the current record's "Yards_15" value
 * @method integer             getHdcp15()                    Returns the current record's "Hdcp_15" value
 * @method integer             getPar16()                     Returns the current record's "Par_16" value
 * @method integer             getYards16()                   Returns the current record's "Yards_16" value
 * @method integer             getHdcp16()                    Returns the current record's "Hdcp_16" value
 * @method integer             getPar17()                     Returns the current record's "Par_17" value
 * @method integer             getYards17()                   Returns the current record's "Yards_17" value
 * @method integer             getHdcp17()                    Returns the current record's "Hdcp_17" value
 * @method integer             getPar18()                     Returns the current record's "Par_18" value
 * @method integer             getYards18()                   Returns the current record's "Yards_18" value
 * @method integer             getHdcp18()                    Returns the current record's "Hdcp_18" value
 * @method integer             getTotInPar()                  Returns the current record's "Tot_in_par" value
 * @method integer             getTotInYards()                Returns the current record's "Tot_in_yards" value
 * @method integer             getLength()                    Returns the current record's "Length" value
 * @method double              getLatitude()                  Returns the current record's "latitude" value
 * @method double              getLongitude()                 Returns the current record's "longitude" value
 * @method Doctrine_Collection getEvents()                    Returns the current record's "Events" collection
 * @method course              setCourseId()                  Sets the current record's "course_id" value
 * @method course              setTeesId()                    Sets the current record's "tees_id" value
 * @method course              setCourseName()                Sets the current record's "CourseName" value
 * @method course              setStreetAddress()             Sets the current record's "StreetAddress" value
 * @method course              setCity()                      Sets the current record's "City" value
 * @method course              setStateorRegion()             Sets the current record's "StateorRegion" value
 * @method course              setZip()                       Sets the current record's "Zip" value
 * @method course              setCounty()                    Sets the current record's "County" value
 * @method course              setPhoneNumber()               Sets the current record's "PhoneNumber" value
 * @method course              setFaxNumber()                 Sets the current record's "FaxNumber" value
 * @method course              setURL()                       Sets the current record's "URL" value
 * @method course              setTotalHoles()                Sets the current record's "TotalHoles" value
 * @method course              setArchitects()                Sets the current record's "architects" value
 * @method course              setYearBuiltFounded()          Sets the current record's "YearBuiltFounded" value
 * @method course              setStatusPublicPrivateResort() Sets the current record's "StatusPublicPrivateResort" value
 * @method course              setGuestPolicy()               Sets the current record's "GuestPolicy" value
 * @method course              setEmailAddress()              Sets the current record's "EmailAddress" value
 * @method course              setTeeNumber()                 Sets the current record's "TeeNumber" value
 * @method course              setTeename()                   Sets the current record's "teename" value
 * @method course              setPar()                       Sets the current record's "Par" value
 * @method course              setHoles()                     Sets the current record's "Holes" value
 * @method course              setRating()                    Sets the current record's "Rating" value
 * @method course              setSlope()                     Sets the current record's "Slope" value
 * @method course              setPar1()                      Sets the current record's "Par_1" value
 * @method course              setYards1()                    Sets the current record's "Yards_1" value
 * @method course              setHdcp1()                     Sets the current record's "Hdcp_1" value
 * @method course              setPar2()                      Sets the current record's "Par_2" value
 * @method course              setYards2()                    Sets the current record's "Yards_2" value
 * @method course              setHdcp2()                     Sets the current record's "Hdcp_2" value
 * @method course              setPar3()                      Sets the current record's "Par_3" value
 * @method course              setYards3()                    Sets the current record's "Yards_3" value
 * @method course              setHdcp3()                     Sets the current record's "Hdcp_3" value
 * @method course              setPar4()                      Sets the current record's "Par_4" value
 * @method course              setYards4()                    Sets the current record's "Yards_4" value
 * @method course              setHdcp4()                     Sets the current record's "Hdcp_4" value
 * @method course              setPar5()                      Sets the current record's "Par_5" value
 * @method course              setYards5()                    Sets the current record's "Yards_5" value
 * @method course              setHdcp5()                     Sets the current record's "Hdcp_5" value
 * @method course              setPar6()                      Sets the current record's "Par_6" value
 * @method course              setYards6()                    Sets the current record's "Yards_6" value
 * @method course              setHdcp6()                     Sets the current record's "Hdcp_6" value
 * @method course              setPar7()                      Sets the current record's "Par_7" value
 * @method course              setYards7()                    Sets the current record's "Yards_7" value
 * @method course              setHdcp7()                     Sets the current record's "Hdcp_7" value
 * @method course              setPar8()                      Sets the current record's "Par_8" value
 * @method course              setYards8()                    Sets the current record's "Yards_8" value
 * @method course              setHdcp8()                     Sets the current record's "Hdcp_8" value
 * @method course              setPar9()                      Sets the current record's "Par_9" value
 * @method course              setYards9()                    Sets the current record's "Yards_9" value
 * @method course              setHdcp9()                     Sets the current record's "Hdcp_9" value
 * @method course              setPar10()                     Sets the current record's "Par_10" value
 * @method course              setYards10()                   Sets the current record's "Yards_10" value
 * @method course              setHdcp10()                    Sets the current record's "Hdcp_10" value
 * @method course              setPar11()                     Sets the current record's "Par_11" value
 * @method course              setYards11()                   Sets the current record's "Yards_11" value
 * @method course              setHdcp11()                    Sets the current record's "Hdcp_11" value
 * @method course              setPar12()                     Sets the current record's "Par_12" value
 * @method course              setYards12()                   Sets the current record's "Yards_12" value
 * @method course              setHdcp12()                    Sets the current record's "Hdcp_12" value
 * @method course              setPar13()                     Sets the current record's "Par_13" value
 * @method course              setYards13()                   Sets the current record's "Yards_13" value
 * @method course              setHdcp13()                    Sets the current record's "Hdcp_13" value
 * @method course              setPar14()                     Sets the current record's "Par_14" value
 * @method course              setYards14()                   Sets the current record's "Yards_14" value
 * @method course              setHdcp14()                    Sets the current record's "Hdcp_14" value
 * @method course              setPar15()                     Sets the current record's "Par_15" value
 * @method course              setYards15()                   Sets the current record's "Yards_15" value
 * @method course              setHdcp15()                    Sets the current record's "Hdcp_15" value
 * @method course              setPar16()                     Sets the current record's "Par_16" value
 * @method course              setYards16()                   Sets the current record's "Yards_16" value
 * @method course              setHdcp16()                    Sets the current record's "Hdcp_16" value
 * @method course              setPar17()                     Sets the current record's "Par_17" value
 * @method course              setYards17()                   Sets the current record's "Yards_17" value
 * @method course              setHdcp17()                    Sets the current record's "Hdcp_17" value
 * @method course              setPar18()                     Sets the current record's "Par_18" value
 * @method course              setYards18()                   Sets the current record's "Yards_18" value
 * @method course              setHdcp18()                    Sets the current record's "Hdcp_18" value
 * @method course              setTotInPar()                  Sets the current record's "Tot_in_par" value
 * @method course              setTotInYards()                Sets the current record's "Tot_in_yards" value
 * @method course              setLength()                    Sets the current record's "Length" value
 * @method course              setLatitude()                  Sets the current record's "latitude" value
 * @method course              setLongitude()                 Sets the current record's "longitude" value
 * @method course              setEvents()                    Sets the current record's "Events" collection
 * 
 * @package    Golf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecourse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course');
        $this->hasColumn('course_id', 'string', 64, array(
             'type' => 'string',
             'primary' => true,
             'length' => 64,
             ));
        $this->hasColumn('tees_id', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('CourseName', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('StreetAddress', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('City', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('StateorRegion', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('Zip', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('County', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('PhoneNumber', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('FaxNumber', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('URL', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('TotalHoles', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('architects', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('YearBuiltFounded', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('StatusPublicPrivateResort', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('GuestPolicy', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('EmailAddress', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('TeeNumber', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('teename', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('Par', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Holes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Rating', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('Slope', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Par_1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_6', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_6', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_6', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_7', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_7', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_7', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_8', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_8', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_8', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_9', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_9', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_9', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_10', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_10', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_10', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_11', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_11', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_11', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_12', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_12', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_12', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_13', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_13', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_13', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_14', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_14', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_14', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_15', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_15', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_15', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_16', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_16', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_16', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_17', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_17', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_17', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Par_18', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Yards_18', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Hdcp_18', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('Tot_in_par', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Tot_in_yards', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Length', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('latitude', 'double', null, array(
             'type' => 'double',
             'default' => 0,
             ));
        $this->hasColumn('longitude', 'double', null, array(
             'type' => 'double',
             'default' => 0,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('event as Events', array(
             'local' => 'course_id',
             'foreign' => 'course_id'));
    }
}