<?php

/**
 * Baseblogs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property text $metadescription
 * @property text $metakeywords
 * @property text $content
 * @property string $filename
 * @property boolean $active
 * @property boolean $deleted
 * @property datetime $publish_date
 * 
 * @method integer  getId()              Returns the current record's "id" value
 * @method string   getTitle()           Returns the current record's "title" value
 * @method text     getMetadescription() Returns the current record's "metadescription" value
 * @method text     getMetakeywords()    Returns the current record's "metakeywords" value
 * @method text     getContent()         Returns the current record's "content" value
 * @method string   getFilename()        Returns the current record's "filename" value
 * @method boolean  getActive()          Returns the current record's "active" value
 * @method boolean  getDeleted()         Returns the current record's "deleted" value
 * @method datetime getPublishDate()     Returns the current record's "publish_date" value
 * @method blogs    setId()              Sets the current record's "id" value
 * @method blogs    setTitle()           Sets the current record's "title" value
 * @method blogs    setMetadescription() Sets the current record's "metadescription" value
 * @method blogs    setMetakeywords()    Sets the current record's "metakeywords" value
 * @method blogs    setContent()         Sets the current record's "content" value
 * @method blogs    setFilename()        Sets the current record's "filename" value
 * @method blogs    setActive()          Sets the current record's "active" value
 * @method blogs    setDeleted()         Sets the current record's "deleted" value
 * @method blogs    setPublishDate()     Sets the current record's "publish_date" value
 * 
 * @package    Golf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseblogs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blogs');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('metadescription', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('metakeywords', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('filename', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('deleted', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('publish_date', 'datetime', null, array(
             'type' => 'datetime',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}