# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            372a25c674968a2a3b330c70567ece6776629cbd
    
    compressed:             true

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    login_module:           index
    login_action:           index

  .actions:
    error_403_module: index   # To be called when a 404 error is raised
    error_403_action: 403   # Or when the requested URL doesn't match any route

    error_404_module: index 
    error_404_action: 404   

    error_405_module: index 
    error_405_action: 405   

    error_500_module: index 
    error_500_action: 500   

    error_503_module: index 
    error_503_action: 503   
