<?php

/**
 * blogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class blogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object blogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('blog');
    }
}