<?php

/**
 * blogsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class blogsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object blogsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('blogs');
    }

    public static function getArticles()
    {
        return Doctrine_Core::getTable( "blogs" )
                                        ->createQuery()
                                        ->where( "deleted = 0 " )
                                        ->orderBy( "publish_date DESC" )
                                        ->execute();//getSqlQuery();
    }
    
    public static function getArticle( $id )
    {
        return Doctrine_Query::create()
                    ->from( "blogs" )
                    ->where( "id = ? ", $id )
                    ->fetchOne();
    }
}