<?php

/**
 * courseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class courseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object courseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('course');
    }
    
    public static function getCourseList( $term )
    {
        $res = Doctrine_Core::getTable( "course" )
                                        ->createQuery()
                                        ->select( "course_id, CourseName")
                                        ->where( "LOWER(CourseName) LIKE '" . trim( strtolower( $term) ) . "%'" )
                                        ->orderBy( "CourseName" )
                                        ->groupBy( "CourseName" )
                                        ->execute();//getSqlQuery();
        $return = Array();
        foreach( $res as $c)
            $return[] = array( "label" => $c->getCourseName()."(".$c->getCourseId().")" );

        return $return;
    }
    
    public static function getStateCourseList( $term )
    {
        $res = Doctrine_Core::getTable( "course" )
                                        ->createQuery()
                                        ->select( "course_id, CourseName")
                                        ->where( "LOWER(StateorRegion) = ? ", trim( strtolower( $term) ) )
                                        ->orderBy( "CourseName" )
                                        ->groupBy( "CourseName" )
                                        ->execute();//getSqlQuery();
        $return = Array();
        foreach( $res as $c)
            $return[] = array( "label" => $c->getCourseName(), "id" => $c->getCourseId() );

        return $return;
    }
    
    public static function getCourseTeesList( $term )
    {
        $res = Doctrine_Core::getTable( "course" )
                                        ->createQuery()
                                        ->select( "tees_id, teename")
                                        ->where( "LOWER(course_id) = ? ", trim( strtolower( $term) ) )
                                        ->orderBy( "teename" )
                                        ->execute();//getSqlQuery();
        $return = Array();
        foreach( $res as $c)
            $return[] = array( "label" => $c->getTeename(), "id" => $c->getTeesId() );

        return $return;
    }
}