<?php

/**
 * courseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class courseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object courseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('course');
    }
}