<?php

/**
 * player
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Golf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class player extends Baseplayer
{
    public function setFirst( $first )
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $result = $q->execute(" UPDATE player SET first = ? WHERE player_id = ? ", array( $first, $this->player_id ) );
    }
    
    public function getFirst()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $result = $q->execute(" SELECT first FROM player WHERE player_id = ? ", array( $this->player_id ) );
    }
    
    public function setLast( $last )
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $result = $q->execute(" UPDATE player SET last = ? WHERE player_id = ? ", array( $last, $this->player_id ) );
    }
    
    public function getLast()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $result = $q->execute(" SELECT last FROM player WHERE player_id = ? ", array( $this->player_id ) );
    }
    
}