<?php

/**
 * player
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Golf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class player extends Baseplayer
{
    public function getScores()
    {
        $ret = array();
//select c.coursename, r.total_score, e.event_date from event c, round b, course a 
//where r.player_id=@player_id and e.event_id=r.event_id and c.tees_id=r.tees_id order by e.event_date desc;        
        $connection = Doctrine_Manager::connection();
        $query = "SELECT 
                        c.coursename AS coursename, 
                        r.total_score AS total_score, 
                        e.event_date AS event_date 
                  FROM event AS e, round AS r, course AS c 
                  WHERE 
                        r.player_id = {$this->player_id} AND 
                        e.event_id = r.event_id AND 
                        c.tees_id = r.tees_id 
                  ORDER BY e.event_date DESC";
        $statement = $connection->execute($query);
        $statement->execute();
        foreach( $statement as $event )
        {
            $temp = array();
            $temp["total_score"] = $event["total_score"];
            $temp["course_name"] = $event["coursename"];
            $temp["event_date"] = $event["event_date"];
            $ret[] = $temp;
        }
        return $ret;
    }
    
    public function getFullName()
    {
        return $this->getFirstName() . " " . $this->getLastName();
    }
    
    public function getAddress()
    {
        return $this->getCity() . ( trim( $this->getState() ) != "" ?  ", " . $this->getState() : "" );
    }
    
}