<?php

/**
 * playerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class playerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object playerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('player');
    }
    
    public static function getUser( $email )
    {
        return Doctrine_Query::create()
                    ->from( "player" )
                    ->select( "email, password" )
                    ->where( "email = ? ", $email )
                    ->fetchOne();
    }
}