<?php

/**
 * roundTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class roundTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object roundTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('round');
    }
}