    <div id="introCellWrapper">
        <div id="introduction"><img src="/images/image_2.jpg" usemap="#Map" border="0" />
            <map name="Map" id="Map">
                <area shape="rect" coords="258,435,418,496" href="https://itunes.apple.com/us/app/golf-gameskeeper/id711522778?mt=8" target="_blank" />
                <area shape="rect" coords="55,436,220,493" href="https://play.google.com/store/apps/details?id=com.golfgameskeeper.mobile" target="_blank" />
            </map>
        </div>
        <div id="cellPhones">
            <div id="wowSlider">
                <!-- Start WOWSlider.com BODY section -->
                <div id="wowslider-container1">
                    <div class="ws_images"><ul>
                            <li><img src="/images/data1/images/slide_7.jpg" alt="slide_7" title="slide_7" id="wows1_0"/></li>
                            <li><img src="/images/data1/images/slide_8.jpg" alt="slide_8" title="slide_8" id="wows1_1"/></li>
                            <li><img src="/images/data1/images/slide_9.jpg" alt="slide_9" title="slide_9" id="wows1_2"/></li>
                            <li><img src="/images/data1/images/slide_10.jpg" alt="slide_10" title="slide_10" id="wows1_3"/></li>
                            <li><img src="/images/data1/images/slide_11.jpg" alt="slide_11" title="slide_11" id="wows1_4"/></li>
                            <li><img src="/images/data1/images/slide_12.jpg" alt="slide_12" title="slide_12" id="wows1_5"/></li>
                            <li><img src="/images/data1/images/slide_13.jpg" alt="slide_13" title="slide_13" id="wows1_6"/></li>
                            <li><img src="/images/data1/images/slide_1.jpg" alt="slide_1" title="slide_1" id="wows1_7"/></li>
                            <li><img src="/images/data1/images/slide_2.jpg" alt="slide_2" title="slide_2" id="wows1_8"/></li>
                            <li><img src="/images/data1/images/slide_3.jpg" alt="slide_3" title="slide_3" id="wows1_9"/></li>
                            <li><img src="/images/data1/images/slide_4.jpg" alt="slide_4" title="slide_4" id="wows1_10"/></li>
                            <li><img src="/images/data1/images/slide_5.jpg" alt="slide_5" title="slide_5" id="wows1_11"/></li>
                            <li><img src="/images/data1/images/slide_6.jpg" alt="slide_6" title="slide_6" id="wows1_12"/></li>
                        </ul></div>
                    <!-- Generated by WOWSlider.com v2.2.3 -->
                    <div class="ws_shadow"></div>
                </div>
<!--                <script type="text/javascript" src="engine1/wowslider.js"></script>
                <script type="text/javascript" src="engine1/script.js"></script>-->
                <!-- End WOWSlider.com BODY section -->
            </div>
        </div>
    </div>
